### PR TITLE
Hw 1

### PR DESCRIPTION
**Pull request by Baltsat**
This pull request includes several significant changes to the repository, focusing on setting up pre-commit checks, configuring linters and formatters, adding comprehensive documentation, and updating the project setup. The most important changes are summarized below:

### Pre-commit Checks and Linters

* [`.github/workflows/pre-commit.yml`](diffhunk://#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036R1-R27): Added a GitHub Actions workflow to run pre-commit checks on every push and pull request. This includes setting up Python, installing dependencies, and running pre-commit hooks.
* [`.pre-commit-config.yaml`](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R1-R9): Configured pre-commit hooks for `black` and `ruff` to ensure code formatting and linting.

### Documentation

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R47): Updated the README file with detailed information about the `TwoHearts_AI` project, including its purpose, functionality, and development roadmap.
* [`docs/ml_system_design_doc.md`](diffhunk://#diff-d7b949294cef983fe5723aeb77fcb841b14159a0a2f02d9ccac418de689725daR1-R372): Added a comprehensive design document for the ML system, covering goals, business requirements, solution methodology, and pilot preparation.

### Project Setup

* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R1-R28): Configured the project with Poetry, specifying dependencies and development tools such as `black`, `ruff`, and `pre-commit`.

### Homework Assignment

* [`hw_1.md`](diffhunk://#diff-2dce82d9a856db037a52f711f84afed621d4a5585791d8736ad735bd5ec7b790R1-R51): Added the first homework assignment, detailing the setup of the project repository, configuration of linters and pre-commit hooks, and the creation of a design document.

service architecture

### CODE REVIEW

**Comment by Baltsat** [comment]
[https://gist.github.com/pacifikus/47424379293e0874859354ecd130ba13](https://gist.github.com/pacifikus/47424379293e0874859354ecd130ba13)

**Review by jamakase — APPROVED** [review]
Лично у меня комментариев как таковых нет, кроме одного - кажется надо было сделать до пункта 2.2.

Но больше - не значит хуже :)

**Comment by anaaaiva** [comment]
Сдано после дедлайна 28.12

**Comment by Baltsat** [comment]
> Сдано после дедлайна 28.12

26-30.11 официально был на конгрессе ученых в Сириусе с ИТМО, рассмотрите прием работы, пожалуйста

**Pull request merged**
